<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TarifPengujianBbpomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tarifData = [
            ['jenis_penerimaan' => 'Uji organoleptik/makroskopik/mikroskopik/keseragaman bobot/ uji zat larut dalam air benda asing/bagian yang tidak larut air/uji suhu lebur/jarak lebur dengan pipa kapiler /uji bobot jenis/uji suhu beku/ uji isi minimum/uji partikel logam (dalam salep mata)/uji bobot tuntas/uji volume terpindahkan/uji kejernihan larutan/uji penetapan volume injeksi dalam wadah/uji rotasi optik/uji kekentalan', 'tarif' => 31257.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Gravimetri (termasuk penetapan susut pengeringan)', 'tarif' => 164944.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Destruksi kering (kadar abu/sisa pemijaran)', 'tarif' => 191319.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Dekstruksi basah dengan microwave', 'tarif' => 249806.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji suhu lebur/jarak lebur dengan thermal analyzer (DSC)', 'tarif' => 333358.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji indeks bias/Uji jarak destilasi', 'tarif' => 190671.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji pH dengan kertas lakmus/indikator universal', 'tarif' => 39390.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji pH dengan pH meter', 'tarif' => 113278.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Ekstraksi cair-cair/Ekstraksi padat-cair (SPE)', 'tarif' => 392015.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Ekstraksi padat-cair dengan immunoaffinity column', 'tarif' => 989143.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Destilasi', 'tarif' => 231883.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji CO2/aktivitas air', 'tarif' => 66704.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji reaksi warna', 'tarif' => 90190.00, 'satuan' => 'Per Senyawa'],
            ['jenis_penerimaan' => 'Reaksi hidrolisis enzimatik/asam/basa', 'tarif' => 170691.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji batas logam berat', 'tarif' => 195627.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Titrimetri, kecuali argentometri', 'tarif' => 301265.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Titrasi argentometri', 'tarif' => 1220325.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Titrimetri dengan potensiometer (kecuali argentometri)', 'tarif' => 472360.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Titrasi argentometri dengan potensiometer', 'tarif' => 1472360.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji spektrofotometri Serapan Atom Flame/Flameless (1-3 senyawa/elemen)', 'tarif' => 682236.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji spektrofotometri Serapan Atom Flame/Flameless (4 senyawa/elemen atau lebih)', 'tarif' => 940875.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji spektrofotometri Serapan Atom dengan Hydride Vapor Generator', 'tarif' => 1193917.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji UV-Vis/Infra merah spektrofotometri', 'tarif' => 731992.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji Inductively Coupled Plasma - Optical Emission Spectrometry (ICPOES)/ ICP-MS (1-3 elemen)', 'tarif' => 1776900.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji Inductively Coupled Plasma - Optical Emission Spectrometry (ICPOES)/ ICP-MS (4 senyawa/elemen atau lebih)', 'tarif' => 2217219.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji raksa dengan merkuri analyzer', 'tarif' => 421202.00, 'satuan' => 'Per Senyawa'],
            ['jenis_penerimaan' => 'Uji kadar air secara titrasi', 'tarif' => 354008.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji kromatografi kertas', 'tarif' => 183243.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji kromatografi lapis tipis', 'tarif' => 389738.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji kromatografi lapis tipis dengan densitometer', 'tarif' => 735895.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji kromatografi gas (1-3 senyawa)', 'tarif' => 853814.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji kromatografi gas (4 senyawa atau lebih)', 'tarif' => 993121.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji kromatografi gas dengan derivatisasi', 'tarif' => 955967.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji GCMS/GCMS-MS (1-3 senyawa)', 'tarif' => 2685703.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji GCMS/GCMS-MS (4 senyawa atau lebih)', 'tarif' => 3216483.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji GCMS/GCMS-MS dengan derivatisasi', 'tarif' => 3164713.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji GCMS-MS Khusus untuk pengujian Dioksin (PCDDs, PCDFs, PCBs)', 'tarif' => 8385699.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji KCKT/UPLC/Kromatografi Ion (1-3 senyawa)', 'tarif' => 851297.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji KCKT/UPLC/Kromatografi Ion (4 senyawa atau lebih)', 'tarif' => 901297.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji KCKT/UPLC/Kromatografi Ion dengan derivatisasi', 'tarif' => 921297.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji LCMS atau LC-MS/MS (1-3 senyawa)', 'tarif' => 2249552.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji LCMS atau LC-MS/MS (4 senyawa atau lebih)', 'tarif' => 2508549.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji LCMS atau LC-MS/MS dengan derivatisasi', 'tarif' => 2528549.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji LC-HRMS', 'tarif' => 4301114.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji ELISA (1-3 sampel)', 'tarif' => 1033041.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji ELISA (4 sampel atau lebih)', 'tarif' => 1258041.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji disolusi menggunakan metode spektrofotometri', 'tarif' => 1003574.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji disolusi menggunakan metode KCKT', 'tarif' => 1550055.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji keseraguman kandungan menggunakan metode spektrofotometri', 'tarif' => 869409.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji keseraguman kandungan menggunakan metode KCKT', 'tarif' => 1342353.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji rokok', 'tarif' => 2560849.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji penetapan kadar metode spektrofotometri (Baku Internasional)', 'tarif' => 1036679.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji penetapan kadar metode KCKT (Baku Internasional)', 'tarif' => 2646040.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji keseraguman kandungan metode spektrofotometri (Baku Internasional)', 'tarif' => 1333632.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji keseraguman kandungan metode KCKT (Baku Internasional)', 'tarif' => 3666765.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji disolusi metode spektrofotometri (Baku Internasional)', 'tarif' => 2281137.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji disolusi metode KCKT (Baku Internasional)', 'tarif' => 3358775.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji Cemaran (Baku Internasional)', 'tarif' => 4300860.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi antibiotik', 'tarif' => 732518.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji sterilitas', 'tarif' => 1763243.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji cemaran mikroba metode kualitatif produk non pangan', 'tarif' => 694576.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji cemaran mikroba metode kuantitatif produk non pangan', 'tarif' => 518980.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji cemaran mikroba metode kualitatif produk pangan (1-3x)', 'tarif' => 728741.00, 'satuan' => '1-4 Sampel per Parameter Uji'],
            ['jenis_penerimaan' => 'Uji cemaran mikroba metode kualitatif produk pangan (4x atau lebih)', 'tarif' => 1642350.00, 'satuan' => '5-10 Sampel per Parameter Uji'],
            ['jenis_penerimaan' => 'Uji cemaran mikroba metode kuantitatif produk pangan (1-3x)', 'tarif' => 669480.00, 'satuan' => '1-4 Sampel per Parameter Uji'],
            ['jenis_penerimaan' => 'Uji cemaran mikroba metode kuantitatif produk pangan (4x atau lebih)', 'tarif' => 1154627.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin Poliomyelitis Oral (OPV)', 'tarif' => 5304417.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi dan stabilitas vaksin OPV', 'tarif' => 7653870.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin Poliomyelitis Terinaktivasi (IPV)', 'tarif' => 3625108.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin campak', 'tarif' => 5650223.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi dan stabilitas vaksin campak', 'tarif' => 7034958.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin BCG', 'tarif' => 2222867.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi dan stabilitas vaksin BCG', 'tarif' => 3022233.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji opasitas vaksin BCG', 'tarif' => 274245.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji identifikasi vaksin BCG dengan pewarnaan', 'tarif' => 227031.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji identifikasi vaksin BCG dengan metode PCR multipleks', 'tarif' => 1720342.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin pertusis/rabies', 'tarif' => 8045065.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin tetanus', 'tarif' => 7941449.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin difteri', 'tarif' => 10105276.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji identifikasi vaksin difteri/tetanus dengan flokulasi', 'tarif' => 704208.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji identifikasi toksoid Tetanus/Difteri dengan ELISA', 'tarif' => 3219239.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin Hepatitis B secara in vivo', 'tarif' => 36981491.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin Hepatitis B secara in vitro', 'tarif' => 3947820.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi anti serum Tetanus/anti serum Difteri', 'tarif' => 2173954.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin HIB dengan metode HPAEC-PAD', 'tarif' => 5471248.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin Influenza', 'tarif' => 2974632.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin Varicella/ JE', 'tarif' => 7613946.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji Penetapan Kandungan Antigen Meningokokus ACYW Roket secara Imunoelektroforesis', 'tarif' => 25908216.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin secara in vitro', 'tarif' => 4860523.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji potensi vaksin secara in vivo', 'tarif' => 8695770.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji pirogenitas', 'tarif' => 5829868.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji iritasi kulit', 'tarif' => 4387701.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji iritasi mata', 'tarif' => 3601756.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji toksisitas khas vaksin pertusis (MWGT)', 'tarif' => 3658441.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji toksisitas khas Difteri Tetanus', 'tarif' => 4282921.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji toksisitas khas tetanus', 'tarif' => 3615463.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji injeksi sistematik', 'tarif' => 2479845.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji endotoksin bakteri (kuantitatif)', 'tarif' => 9775089.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji endotoksin bakteri (semi kuantitatif)', 'tarif' => 5820596.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji mikrobakterium vaksin BCG', 'tarif' => 5120139.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Pembacaan ulang preparat NVT tipe 3', 'tarif' => 2210490.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Pembacaan ulang preparat NVT tipe 1 atau 2', 'tarif' => 1645737.00, 'satuan' => 'Per Pengujian'],
            ['jenis_penerimaan' => 'Uji Screening Genetic Modified Organism (GMO)', 'tarif' => 4578009.00, 'satuan' => 'Per Sampel'],
            ['jenis_penerimaan' => 'Uji identifikasi DNA spesifik spesies produk olahan kompleks Realtime PCR', 'tarif' => 4578009.00, 'satuan' => 'Per Sampel'],
            ['jenis_penerimaan' => 'Uji identifikasi DNA spesifik spesies produk olahan sederhana Realtime PCR', 'tarif' => 1877952.00, 'satuan' => 'Per Sampel'],
        ];

        DB::table('tarif_pengujian_bbpom')->insert($tarifData);
    }
}
